# Generated by Django 5.0.2 on 2024-03-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка оплаты')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Продукт')),
            ],
        ),
    ]
